url: https://pelagornis.github.io/styleguide/
title: Pelagornis Style Guide
description: "Style guides for Pelagornis open-source projects"
timezone: Asia/Seoul
safe: true
future: true
asset_url: /assets
highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
