url: https://pelagornis.github.io
title: Pelagornis Style Guide
description: "Style guides for Pelagornis open-source projects"
timezone: Asia/Seoul
safe: true
future: true

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from